  0%|          | 0/4 [00:00<?, ?it/s]100%|██████████| 4/4 [00:00<00:00, 52.60it/s]
  0%|          | 0/15620 [00:00<?, ?it/s]  7%|▋         | 1046/15620 [00:00<00:01, 10453.78it/s] 14%|█▍        | 2204/15620 [00:00<00:01, 11115.56it/s] 22%|██▏       | 3363/15620 [00:00<00:01, 11331.37it/s] 29%|██▉       | 4533/15620 [00:00<00:00, 11472.71it/s] 36%|███▋      | 5681/15620 [00:00<00:00, 11431.50it/s] 44%|████▍     | 6875/15620 [00:00<00:00, 11603.02it/s] 52%|█████▏    | 8074/15620 [00:00<00:00, 11725.38it/s] 59%|█████▉    | 9289/15620 [00:00<00:00, 11860.13it/s] 67%|██████▋   | 10493/15620 [00:00<00:00, 11914.27it/s] 75%|███████▍  | 11704/15620 [00:01<00:00, 11971.58it/s] 83%|████████▎ | 12902/15620 [00:01<00:00, 11971.25it/s] 90%|█████████ | 14102/15620 [00:01<00:00, 11979.83it/s] 98%|█████████▊| 15316/15620 [00:01<00:00, 12027.64it/s]100%|██████████| 15620/15620 [00:01<00:00, 11766.99it/s]
  0%|          | 0/80 [00:00<?, ?it/s]100%|██████████| 80/80 [00:00<00:00, 11705.31it/s]
Traceback (most recent call last):
  File "main_abl.py", line 460, in <module>
    attention_rescale=args.attention_rescale)
TypeError: __init__() got an unexpected keyword argument 'op_fp_gcn_out_dims'
slurmstepd: error: *** JOB 1087840 ON joachims-compute-02 CANCELLED AT 2023-10-17T11:08:54 ***
